# Generated by Django 6.0.2 on 2026-02-19 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('home_type', models.CharField(choices=[('Old Age Home', 'Old Age Home'), ('Orphanage', 'Orphanage'), ('Shelter', 'Shelter'), ('NGO', 'NGO')], max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('residents', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
