# Generated by Django 6.0.2 on 2026-02-25 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_donor_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('cooked_time', models.TimeField(blank=True, null=True)),
                ('pickup_deadline', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('packaging', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
