# Generated by Django 6.0.2 on 2026-03-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pickup_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
